sudo: required
language: rust
matrix:
    include:
        - rust: nightly
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq apt-utils build-essential pciutils linux-headers-`uname -r` python python3  libssl-dev 
    - sudo apt-get install -qq libgnutls30 libgnutls-openssl-dev libcurl4-gnutls-dev cmake bash libpcap-dev
services:
    - docker
script:
    - ./build.sh build
install: true
