sudo: required
language: sh
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq apt-utils build-essential pciutils linux-headers-`uname -r` python python3  libssl-dev 
    - sudo apt-get install -qq libgnutls28 libgnutls-dev libcurl4-gnutls-dev cmake bash libpcap-dev
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
services:
    - docker
script:
    - ./build.sh build
    - ./build.sh build_container
install: true
