[package]
name = "e2d2"
version = "0.1.0"
authors = ["Aurojit Panda <apanda@cs.berkeley.edu>"]
build = "build.rs"

[lib]
doctest = false

[dependencies]
libc = ">= 0.2.4"
time = ">=0.1.0"
simd = { git = "https://github.com/huonw/simd" }
getopts = "*"
byteorder = "*"
clippy = { version = "*", optional = true }
fnv = "*"
twox-hash = "*"
regex = "*"
lazy_static = "*"

[profile.release]
opt-level = 3
lto = true
rpath = true
debug = false # We turn debug symbols off because of a bug
debug-assertions = false

[features]
default = []
performance = []
dev = ["clippy"]
